Num_Layers: 2

I: 4
F: 4
defval: 1000

N: 1
C: 3
Orig_H: 32
Orig_W: 32
K: 4
Kc: 2
S: 5
R: 5
PE_Num_H: 7
PE_Num_W: 7
io_sparsity: 0.6
w_sparsity: 0.6

N: 1
C: 4
Orig_H: 16
Orig_W: 16
K: 8
Kc: 4
S: 3
R: 3
PE_Num_H: 7
PE_Num_W: 7
io_sparsity: 0.8
w_sparsity: 0.7