Num_Layers: 2

I: 4
F: 4
defval: 5

N: 1
C: 3
Orig_H: 56
Orig_W: 56
K: 4
Kc: 2
S: 3
R: 3
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.3
w_sparsity: 0.59

N: 1
C: 4
Orig_H: 37
Orig_W: 37
K: 4
Kc: 1
S: 5
R: 5
PE_Num_H: 7
PE_Num_W: 7
io_sparsity: 0
w_sparsity: 0.59