Num_Layers: 5

I: 4
F: 4
defval: 1000

N: 1
C: 3
Orig_H: 64
Orig_W: 64
K: 4
Kc: 2
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.6
w_sparsity: 0.6

N: 2
C: 3
Orig_H: 32
Orig_W: 32
K: 4
Kc: 2
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.6
w_sparsity: 0.6

N: 3
C: 3
Orig_H: 32
Orig_W: 32
K: 4
Kc: 2
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.6
w_sparsity: 0.6

N: 4
C: 3
Orig_H: 32
Orig_W: 32
K: 4
Kc: 2
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.6
w_sparsity: 0.6

N: 5
C: 3
Orig_H: 32
Orig_W: 32
K: 4
Kc: 2
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.6
w_sparsity: 0.6