Num_Layers: 12

I: 4
F: 4
defval: 100

N: 1  # inception_3a_pool_proj
C: 32
Orig_H: 28
Orig_W: 28
K: 32
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.04
w_sparsity: 0.57

N: 1  # inception_3a_1x1
C: 192
Orig_H: 28
Orig_W: 28
K: 64
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.29
w_sparsity: 0.62

N: 1  # inception_3a_3x3_reduce
C: 192
Orig_H: 28
Orig_W: 28
K: 96
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.29
w_sparsity: 0.58

N: 1  # inception_3a_3x3
C: 96
Orig_H: 28
Orig_W: 28
K: 128
Kc: 8
S: 3
R: 3
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.33
w_sparsity: 0.55

N: 1  # inception_3a_5x5_reduce
C: 192
Orig_H: 28
Orig_W: 28
K: 16
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.29
w_sparsity: 0.64

N: 1  # inception_3a_5x5
C: 16
Orig_H: 28
Orig_W: 28
K: 32
Kc: 8
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.23
w_sparsity: 0.65

N: 1  # inception_5a_pool_proj
C: 128
Orig_H: 7
Orig_W: 7
K: 128
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.43
w_sparsity: 0.68

N: 1  # inception_5a_1x1
C: 1024
Orig_H: 7
Orig_W: 7
K: 384
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.69
w_sparsity: 0.68

N: 1  # inception_5a_3x3_reduce
C: 1024
Orig_H: 7
Orig_W: 7
K: 192
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.69
w_sparsity: 0.67

N: 1  # inception_5a_3x3
C: 192
Orig_H: 7
Orig_W: 7
K: 384
Kc: 8
S: 3
R: 3
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.7
w_sparsity: 0.63

N: 1  # inception_5a_5x5_reduce
C: 1024
Orig_H: 7
Orig_W: 7
K: 48
Kc: 8
S: 1
R: 1
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.69
w_sparsity: 0.67

N: 1  # inception_5a_5x5
C: 48
Orig_H: 7
Orig_W: 7
K: 128
Kc: 8
S: 5
R: 5
PE_Num_H: 8
PE_Num_W: 8
io_sparsity: 0.54
w_sparsity: 0.64